name: NestJS App

on:
  pull_request:
    branches: [develop, main]

env:
  DOCKER_BUILDKITE: 1
  NODE_VERSION: 20.x

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install NestJS CLI
        run: npm install -g @nestjs/cli

      - name: Lint
        run: |
          npm ci
          npm run lint

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          npm run build

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |
          npm run test

  # docker:
  #   name: Docker Operations
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Login to Docker Registry
  #     uses: docker/login-action@v2
  #     with:
  #       registry: ${{ secrets.DOCKER_REGISTRY }}
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_PASSWORD }}

  #   - name: Build and Push with Docker Compose
  #     run: |
  #       docker-compose -f docker-compose.ci.yml build
  #       docker-compose -f docker-compose.ci.yml push

  #   - name: Scan Images (optional)
  #     run: |
  #       docker scan --file auth-service/Dockerfile your-registry/auth-service:latest
